CREATE DATABASE IF NOT EXISTS CRM_DEMO;
USE CRM_DEMO;
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  ID         INTEGER(16) AUTO_INCREMENT,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME  VARCHAR(30) NOT NULL,
  EMAIL      VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET =UTF8;

INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Yao', 'Xiao', 'yao.xiao@hp.com');

INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('John', 'Smith', 'john.smith@example.com');